/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#71a1ff",
        "surface-bright": "#f8f9ff",
        "primary-container": "#10b981",
        "on-surface": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "tertiary": "#005ac2",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#3c475a",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed": "#d8e3fb",
        "on-surface-variant": "#3c4a42",
        "background": "#f8f9ff",
        "surface-container": "#e5eeff",
        "on-tertiary-container": "#00367a",
        "tertiary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed-variant": "#004395",
        "surface-container-high": "#dce9ff",
        "on-secondary-container": "#586377",
        "tertiary-fixed": "#d8e2ff",
        "surface-dim": "#cbdbf5",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed": "#111c2d",
        "surface-container-low": "#eff4ff",
        "secondary": "#545f73",
        "on-error-container": "#93000a",
        "outline-variant": "#bbcabf",
        "on-tertiary-fixed": "#001a42",
        "surface": "#f8f9ff",
        "surface-tint": "#006c49",
        "error-container": "#ffdad6",
        "secondary-container": "#d5e0f8",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#4edea3",
        "inverse-surface": "#213145",
        "on-primary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed": "#002113",
        "secondary-fixed-dim": "#bcc7de",
        "outline": "#6c7a71",
        "on-primary-fixed-variant": "#005236",
        "inverse-primary": "#4edea3",
        "on-background": "#0b1c30",
        "primary": "#006c49"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "section-gap": "48px",
        "gutter": "24px",
        "container-padding-mobile": "16px",
        "base": "8px",
        "container-padding-desktop": "40px",
        "card-gap": "24px"
      },
      "fontFamily": {
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      "fontSize": {
        "label-sm": ["11px", {"lineHeight": "12px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
