// mailer.config.js

const nodemailer = require('nodemailer');
const { config } = require('./index.config');

const transporter = nodemailer.createTransport({
  host: config.SMTP_HOST,
  port: config.SMTP_PORT,
  secure: false,
  auth: {
    user: config.SMTP_USER,
    pass: config.SMTP_PASS,
  },
});

async function sendVerificationEmail(email, token) {
  const verifyUrl = `${config.FRONTEND_URL}/verify-email?token=${token}`;

  await transporter.sendMail({
    from: `"WealthFlow" <${config.SMTP_USER}>`,
    to: email,
    subject: 'Verify your email',
    html: `
      <p>Click the link below to verify your email. It expires in 24 hours.</p>
      <a href="${verifyUrl}">${verifyUrl}</a>
    `,
  });
}

async function sendPasswordResetEmail(email, code) {
  await transporter.sendMail({
    from: `"WealthFlow" <${config.SMTP_USER}>`,
    to: email,
    subject: 'Your password reset code',
    html: `
      <p>Your password reset code is:</p>
      <h2 style="letter-spacing: 8px;">${code}</h2>
      <p>This code expires in 15 minutes.</p>
      <p>If you didn't request this, ignore this email.</p>
    `,
  });
}

async function sendWeeklyInsightsEmail(email, name, insights) {
  const {
    summary,
    thisWeekTotal,
    lastWeekTotal,
    diff,
    direction,
    thisWeekTotals,
  } = insights;

  const categoryRows = Object.entries(thisWeekTotals)
    .sort((a, b) => b[1] - a[1])
    .map(([cat, amt]) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #f0f0f0;">${cat}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #f0f0f0;text-align:right;font-weight:500;">
          $${Number(amt).toFixed(2)}
        </td>
      </tr>`)
    .join('');

  await transporter.sendMail({
    from: `"WealthFlow" <${config.SMTP_USER}>`,
    to: email,
    subject: `Your weekly spending summary — ${direction === 'more' ? '📈' : '📉'} $${diff} ${direction} than last week`,
    html: `
      <div style="max-width:600px;margin:0 auto;font-family:'Helvetica Neue',sans-serif;color:#1a1a1a;">

        <!-- Header -->
        <div style="background:#1D9E75;padding:32px 40px;border-radius:12px 12px 0 0;">
          <h1 style="margin:0;color:#fff;font-size:22px;font-weight:600;">WealthFlow</h1>
          <p style="margin:6px 0 0;color:rgba(255,255,255,0.8);font-size:14px;">Weekly Spending Insights</p>
        </div>

        <!-- Body -->
        <div style="background:#fff;padding:32px 40px;border:1px solid #eee;border-top:none;">
          <p style="font-size:15px;margin:0 0 24px;">Hi ${name},</p>

          <!-- Stats -->
          <div style="display:flex;gap:16px;margin-bottom:28px;">
            <div style="flex:1;background:#f7f6f3;border-radius:10px;padding:16px 20px;">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:4px;">This week</div>
              <div style="font-size:24px;font-weight:600;">$${thisWeekTotal}</div>
            </div>
            <div style="flex:1;background:#f7f6f3;border-radius:10px;padding:16px 20px;">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:4px;">Last week</div>
              <div style="font-size:24px;font-weight:600;">$${lastWeekTotal}</div>
            </div>
            <div style="flex:1;background:${direction === 'more' ? '#fef3f2' : '#f0faf6'};border-radius:10px;padding:16px 20px;">
              <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:4px;">Change</div>
              <div style="font-size:24px;font-weight:600;color:${direction === 'more' ? '#e24b4a' : '#1D9E75'};">
                ${direction === 'more' ? '+' : '-'}$${diff}
              </div>
            </div>
          </div>

          <!-- AI Summary -->
          <div style="background:#f7f6f3;border-radius:10px;padding:20px 24px;margin-bottom:28px;line-height:1.7;font-size:14px;">
            ${summary.replace(/\n/g, '<br>')}
          </div>

          <!-- Category breakdown -->
          <h3 style="font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:0.08em;color:#888;margin:0 0 12px;">
            This week by category
          </h3>
          <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:28px;">
            ${categoryRows}
          </table>

          <p style="font-size:13px;color:#aaa;margin:0;">
            This summary was generated by WealthFlow AI every Monday morning.
          </p>
        </div>

        <!-- Footer -->
        <div style="background:#f7f6f3;padding:20px 40px;border-radius:0 0 12px 12px;border:1px solid #eee;border-top:none;">
          <p style="margin:0;font-size:12px;color:#bbb;text-align:center;">
            WealthFlow · You're receiving this because you have an active account.
          </p>
        </div>
      </div>
    `,
  });
}


module.exports = { 
  sendVerificationEmail,
  sendPasswordResetEmail,
};
